# Project: unit4
# Makefile created by Dev-C++ 5.6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 4.8_7.o
LINKOBJ  = 4.8_7.o
LIBS     = -L"D:/codesoftwares/Dev-Cpp/MinGW64/lib" -L"D:/codesoftwares/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/codesoftwares/Dev-Cpp/MinGW64/include" -I"D:/codesoftwares/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/codesoftwares/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/codesoftwares/Dev-Cpp/MinGW64/include" -I"D:/codesoftwares/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/codesoftwares/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/codesoftwares/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = unit4.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

4.8_7.o: 4.8_7.c
	$(CC) -c 4.8_7.c -o 4.8_7.o $(CFLAGS)
