# Project: unit7
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 7_12_9.o
LINKOBJ  = 7_12_9.o
LIBS     = -L"D:/codesoftwares/Dev-Cpp/MinGW64/lib" -L"D:/codesoftwares/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/codesoftwares/Dev-Cpp/MinGW64/include" -I"D:/codesoftwares/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
CXXINCS  = -I"D:/codesoftwares/Dev-Cpp/MinGW64/include" -I"D:/codesoftwares/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
BIN      = unit7.exe
CXXFLAGS = $(CXXINCS) -std=c99
CFLAGS   = $(INCS) -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

7_12_9.o: 7_12_9.c
	$(CC) -c 7_12_9.c -o 7_12_9.o $(CFLAGS)
